Repository Orbital-Knewbie/Knewbie, pull requests merged in 2020-07, with the labels that each got.

#80 Update README.md
  README.md
Labels: documentation

#82 Update Links to link documents from wiki
  README.md
  docs/DevPractices.md
  docs/DeveloperGuide.md
  docs/InstallationGuide.md
  docs/UserGuide-Educator.md
  docs/UserGuide-Students.md
Labels: developer practices, documentation

#86 Class/Quiz Integration
  Knewbie1.pyproj
  app.db
  app/auth/forms.py
  app/auth/views.py
  app/group/forms.py
  app/group/group.py
  app/group/views.py
  app/main/forms.py
  app/main/views.py
  app/models.py
  app/quiz/cat.py
  app/quiz/forms.py
  app/quiz/questions.py
  app/quiz/views.py
  app/static/content/faqstyle.css
  app/static/content/settingstyle.css
  app/static/content/style.css
  app/static/scripts/script.js
  app/templates/_formhelpers.html
  app/templates/auth/deactivate.html
  app/templates/base.html
  app/templates/faq.html
  app/templates/group/classquiz.html
  app/templates/quiz/createqn.html
  app/templates/quiz/createquizsuccess.html
  app/templates/quiz/previewquiz.html
  app/templates/quiz/quiz.html
  app/templates/quiz/result.html
  app/templates/settings.html
  app/templates/sidebar.html
  app/tests/test_auth.py
  app/tests/test_classquiz.py
Labels: enhancement

#88 Address Prototype Feedback
  app/static/content/contactstyle.css
  app/static/content/dashboardstyle.css
  app/static/content/faqstyle.css
  app/static/content/homepagestyle.css
  app/static/content/quizstyle.css
  app/static/content/style.css
  app/templates/base.html
  app/templates/dashboard.html
Labels: enhancement

#89 Class Settings, Documentation
  Knewbie1.pyproj
  app.db
  app/templates/group/classsettings.html
  docs/diagrams/Controller.png
  docs/diagrams/Controller.puml
  docs/diagrams/CreateQuizSequence.png
  docs/diagrams/CreateQuizSequence.puml
  docs/diagrams/Database.png
  docs/diagrams/Database.puml
  docs/diagrams/View.png
  docs/diagrams/View.puml
  migrations/versions/30d33d3cefe3_init_db.py
  migrations/versions/9bf74eda21d2_question_image.py
Labels: bug, developer practices, documentation

#90 Add Progress Report functionalities
  app.db
  app/main/profile.py
  app/main/views.py
  app/quiz/questions.py
  app/quiz/views.py
  app/templates/report.html
Labels: enhancement

#91 Fix Progress Report Name
  README.md
  app/templates/report.html
Labels: bug, documentation

#92 Update sidebar.html
  app/templates/sidebar.html
Labels: bug

#93 Fix bug accessing tailored quiz after completion
  app.db
  app/quiz/views.py
  app/templates/dashboard.html
Labels: bug
