Repository Orbital-Knewbie/Knewbie, pull requests merged in 2020-06, with the labels that each got.

#41 Update Installation Guide and Create Developer Practices
  Knewbie1.pyproj
  README.md
  app/views.py
  docs/DevPractices.md
  docs/DeveloperGuide.md
  docs/InstallationGuide.md
  docs/images/BuildEssential.png
  docs/images/Clone.png
  docs/images/Configure.png
  docs/images/DownloadPython.png
  docs/images/DownloadVenv.png
  docs/images/EnterVenv.png
  docs/images/FlaskRun.png
  docs/images/Kanban.png
  docs/images/Make.png
  docs/images/Requirements.png
  docs/images/Scrum.png
Labels: documentation

#44 Update Database, Quiz and Forum
  Knewbie1.pyproj
  app.db
  app/cat.py
  app/forms.py
  app/forum.py
  app/models.py
  app/questions.py
  app/templates/base.html
  app/templates/forum.html
  app/templates/posts.html
  app/views.py
  docs/DevPractices.md
  docs/DeveloperGuide.md
  docs/ProjectLog.md
  docs/diagrams/Controller.png
  docs/diagrams/Controller.puml
  docs/diagrams/Database.png
  docs/diagrams/Database.puml
  docs/diagrams/QuizSequence.png
  docs/diagrams/QuizSequence.puml
  docs/diagrams/UserEntity.png
  docs/diagrams/UserEntity.puml
  migrations/versions/258840be36fa_init_db.py
  run.py
Labels: documentation, enhancement

#45 Deactivate button and routing
  Knewbie1.pyproj
  app.db
  app/__init__.py
  app/email.py
  app/errors/__init__.py
  app/errors/handlers.py
  app/forms.py
  app/static/content/loginstyle.css
  app/static/content/settingstyle.css
  app/templates/403.html
  app/templates/410.html
  app/templates/500.html
  app/templates/dashboard.html
  app/templates/deactivate.html
  app/templates/errors/error403.html
  app/templates/errors/error404.html
  app/templates/errors/error410.html
  app/templates/errors/error500.html
  app/templates/settings.html
  app/views.py
Labels: bug, enhancement

#53 Update README
  README.md
Labels: developer practices, documentation

#49 R-Ramana-Create-Form-Edu
  Knewbie1.pyproj
  app.db
  app/errors/handlers.py
  app/forms.py
  app/forum.py
  app/models.py
  app/profile.py
  app/static/content/createstyle.css
  app/static/content/dashboardstyle.css
  app/static/content/leaderboardstyle.css
  app/static/content/quizstyle.css
  app/static/content/sidebarstyle.css
  app/static/scripts/script.js
  app/templates/createclasssuccess.html
  app/templates/createqn.html
  app/templates/createquizsuccess.html
  app/templates/dashboard.html
  app/templates/leaderboard.html
  app/templates/quiz.html
  app/templates/sidebar.html
  app/views.py
  migrations/versions/0dbf7a4b7a10_.py
Labels: enhancement

#55 Clean up styling for educator's dashboard
  app.db
  app/static/content/createstyle.css
  app/static/content/dashboardstyle.css
Labels: enhancement

#56 Changes to reflect educator vs student account
  app.db
  app/forms.py
  app/templates/createclasssuccess.html
  app/templates/dashboard.html
  app/templates/leaderboard.html
  app/templates/settings.html
  app/templates/sidebar.html
  docs/images/Change_Code.png
  docs/images/Class_Success.png
  docs/images/Create.png
  docs/images/Create_Qn.png
  docs/images/Deactivate.png
  docs/images/Deactivate_Email.png
  docs/images/Leaderboard.png
  docs/images/ProgressReport.png
  docs/images/Quiz_Success.png
  docs/images/Settings_Account.png
  docs/images/Settings_Default.png
  docs/images/Settings_Default_Edu.png
Labels: documentation

#62 Style main Forum page accessible by class, delete class page and form
  Knewbie1.pyproj
  app.db
  app/forms.py
  app/static/content/forumstyle.css
  app/static/content/poststyle.css
  app/static/content/sidebarstyle.css
  app/templates/deactivate.html
  app/templates/deleteclass.html
  app/templates/forum.html
  app/templates/participants.html
  app/templates/posts.html
  app/templates/register.html
  app/templates/sidebar.html
  app/views.py
Labels: bug, enhancement

#66 Add feature implementations for Class / Forum / Quiz, Unit Tests
  Knewbie1.pyproj
  app.db
  app/forms.py
  app/forum.py
  app/group.py
  app/models.py
  app/questions.py
  app/templates/base.html
  app/templates/classquizzes.html
  app/templates/createclasssuccess.html
  app/templates/createqn.html
  app/templates/createquizsuccess.html
  app/templates/dashboard.html
  app/templates/deleteclass.html
  app/templates/index.html
  app/templates/participants.html
  app/templates/posts.html
  app/templates/previewquiz.html
  app/templates/quiz.html
  app/templates/result.html
  app/templates/sidebar.html
  app/tests/__init__.py
  app/tests/test.db
  app/tests/test_basic.py
  app/tests/test_users.py
  app/views.py
  tests/test_1.py
Labels: developer practices, enhancement

#73 Unit Testing, Progress Report, Class Quizzes, Quiz Preview & Results, Travis, codecov
  .gitignore
  .travis.yml
  Knewbie1.pyproj
  Procfile
  README.md
  app.db
  app/__init__.py
  app/cat.py
  app/email.py
  app/forms.py
  app/forum.py
  app/group.py
  app/models.py
  app/profile.py
  app/questions.py
  app/static/content/dashboardstyle.css
  app/static/content/forumstyle.css
  app/static/content/homepagestyle.css
  app/static/content/leaderboardstyle.css
  app/static/content/poststyle.css
  app/static/content/quizstyle.css
  app/templates/base.html
  app/templates/classquiz.html
  app/templates/dashboard.html
  app/templates/forum.html
  app/templates/index.html
  app/templates/leaderboard.html
  app/templates/login.html
  app/templates/participants.html
  app/templates/posts.html
  app/templates/previewquiz.html
  app/templates/quiz.html
  app/templates/report.html
  app/templates/result.html
  app/templates/sidebar.html
  app/tests/basetest.py
  app/tests/test.db
  app/tests/test_auth.py
  app/tests/test_basic.py
  app/tests/test_groups.py
  app/tests/test_quiz.py
  app/tests/test_users.py
  app/views.py
  docs/DevPractices.md
  docs/DeveloperGuide.md
  docs/diagrams/Database.png
  docs/diagrams/Database.puml
  docs/images/unittest.png
  install.py
  migrations/versions/93617144d712_init_db.py
  requirements.txt
Labels: developer practices, documentation, enhancement

#78 Update Unit Tests
  Knewbie1.pyproj
  app/questions.py
  app/templates/quiz.html
  app/tests/basetest.py
  app/tests/test.db
  app/tests/test_auth.py
  app/tests/test_basic.py
  app/tests/test_forum.py
  app/tests/test_groups.py
  app/tests/test_quiz.py
  app/tests/test_users.py
  app/views.py
  docs/DeveloperGuide.md
Labels: developer practices

#79 Routing back home from error messages and custom loading screen
  app/static/content/errorstyle.css
  app/static/content/style.css
  app/static/scripts/script.js
  app/templates/base.html
  app/templates/errors/error403.html
  app/templates/errors/error404.html
  app/templates/errors/error410.html
  app/templates/errors/error500.html
Labels: enhancement
